enum UserActions {
  SET_USER_ID = 'SET_USER_ID',
  SET_FIRST_NAME = 'SET_FIRST_NAME',
  SET_LAST_NAME = 'SET_LAST_NAME',
  SET_USER_PIC_URL = 'SET_USER_PIC_URL',
  SIGN_OUT_CLEAR = 'SIGN_OUT_CLEAR',
}

export { UserActions }